# SPDX-FileCopyrightText: Copyright (c) 2025-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT

[tool.poetry]
name = "flake8-code-free-tests"
description = "Flake8 plugin to enforce control-flow-free test functions"
version = "0.0.1"
license = "MIT"

authors = []

readme = "README.md"

repository = "https://github.com/blablatdinov/flake8-code-free-tests"

keywords = []

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.10"
flake8 = "^7.1"

[tool.poetry.plugins."flake8.extension"]
CFT = "flake8_code_free_tests.plugin:Plugin"

[tool.poetry.group.dev.dependencies]
mypy = "1.20.2"
ruff = "0.14.14"
wemake-python-styleguide = "1.5.0"
pytest = "9.1.1"
pytest-cov = "7.0.0"
pytest-randomly = "4.0.1"
astpretty = "3.0.0"

[build-system]
requires = ["poetry-core>=1.9.0"]
build-backend = "poetry.core.masonry.api"
